name: Rubika Cloud Uploader

on:
  workflow_dispatch:
    inputs:
      file_url:
        description: 'لینک فایل:'
        required: true
      part_size:
        description: 'سایز هر فایل به مگابایت از 100 تا 1990 (1000 توصیه میشود)'
        required: false
        default: 1000

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install rubpy

      - name: Download File
        run: |
          mkdir -p downloads/parts
          curl -L "${{ github.event.inputs.file_url }}" -o "downloads/main_file"

      - name: Split File (1GB Chunks)
        run: |
          split -b ${{ github.event.inputs.part_size }}M -d "downloads/main_file" "downloads/parts/part_"
          rm "downloads/main_file"

      - name: Restore Rubika Session
        run: |
          echo "${{ secrets.SESSION_FILE_BASE64 }}" | base64 -d > user_session.rp

      - name: Run Uploader
        run: python rubika_uploader.py
